commitment_hash = "0x042cf71f7e7ebd3fbd6f5a1807f1894c1d738690451e51516070c1688e2f3c96"
merkle_root = "0x0ae4b821bcbfcc5f6a3b711a48ceb8a86baad969d64fb90cfd2e2b3670e37dc7"

merkle_path = ["0x000000000000000000000000000000000000000000000000000000617070656c", "0x21b8caea37e4c2b977393f1e99e1faa94f50bb9d8a6a2887eda2ee13c838c509", "0x2b51f5a296bc4e5ad0b35dcb0d29c8b8a57da23856ae581fdd2bade16d23cd47", "0x1e72357f512579c721f34d90a34e918e522f6c9b6c0214c22d6983739360bd2b", "0x200d4875be60d7de4dcc7a8236261b41cd69ae48a9f101ac1cdadea808c6055d", "0x20c3110c03396f3e2d4a68f060b249a9397bfe629a236661d3b6170158ad1004", "0x029da372053a7b3d33066b393430e74c2b57d4bdc707aebef53cd39baac39bf7", "0x05771b4c0f38e70640fb7bc56718a49ff89748bd0fdda200b688b10b9bdc2b0f", "0x2d57e69f27b05caf7bd45ef2a2e377dddcae114ba35c959c356e974a9dbda57d", "0x10799a023ff61378f739449c42e441531b5ec1d653a14bd13cbf8b5942ce8313", "0x2b1fe02dc0f8dcf3c886a0c45211aff822b2369b6a79105544307bb2aec75ae5", "0x2d58f21f40828ad9da016e9a65e6eb094738d413675c1e1ee6a23fea46a43265", "0x1bfb08cb2d09d49d0b44bf005f03f38daedab3bda6260c5c80d2790a9504519f", "0x145448670d2ad4086f2fd5149779f037deef60525196e5c6972e52b162627576"]
merkle_indices = [1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0]

first_letter = "97"
second_letter = "112"
third_letter = "112"
fourth_letter = "108"
fifth_letter = "101"
salt = "0"
