calculated_result = [2, 2, 2, 1, 0]
commitment_hashes = "0x042cf71f7e7ebd3fbd6f5a1807f1894c1d738690451e51516070c1688e2f3c96"
fifth_letter = "101"
fifth_letter_guess = "111"
first_letter = "97"
first_letter_guess = "97"
fourth_letter = "108"
fourth_letter_guess = "97"
salt = "0"
second_letter = "112"
second_letter_guess = "112"
third_letter = "112"
third_letter_guess = "112"
